import type { Company, Contact, Tag } from "./types";

export const initialTags: Tag[] = [
  { id: "t1", name: "Warm" },
  { id: "t2", name: "Cold" },
  { id: "t3", name: "Referral" },
  { id: "t4", name: "Priority" },
  { id: "t5", name: "Investor" },
  { id: "t6", name: "Design" },
  { id: "t7", name: "Engineering" },
];

export const initialCompanies: Company[] = [
  {
    id: "c1",
    name: "Linear",
    website: "https://linear.app",
    linkedin: "https://linkedin.com/company/linear",
    size: "51-200",
    created_at: "2026-05-11T10:00:00Z",
  },
  {
    id: "c2",
    name: "Vercel",
    website: "https://vercel.com",
    linkedin: "https://linkedin.com/company/vercel",
    size: "201-500",
    created_at: "2026-06-02T10:00:00Z",
  },
  {
    id: "c3",
    name: "Notion",
    website: "https://notion.so",
    linkedin: "https://linkedin.com/company/notion",
    size: "500+",
    created_at: "2026-06-18T10:00:00Z",
  },
  {
    id: "c4",
    name: "Raycast",
    website: "https://raycast.com",
    linkedin: "https://linkedin.com/company/raycast",
    size: "11-50",
    created_at: "2026-07-01T10:00:00Z",
  },
  {
    id: "c5",
    name: "Arc",
    website: "https://arc.net",
    linkedin: "https://linkedin.com/company/thebrowserco",
    size: "51-200",
    created_at: "2026-07-08T10:00:00Z",
  },
];

export const initialContacts: Contact[] = [
  {
    id: "p1",
    company_id: "c1",
    name: "Karri Saarinen",
    role: "CEO & Co-founder",
    email: "karri@linear.app",
    linkedin: "https://linkedin.com/in/karrisaarinen",
    twitter: "https://twitter.com/karrisaarinen",
    status: "in_conversation",
    created_at: "2026-06-05T12:00:00Z",
    tag_ids: ["t1", "t4", "t6"],
  },
  {
    id: "p2",
    company_id: "c2",
    name: "Guillermo Rauch",
    role: "CEO",
    email: null,
    linkedin: "https://linkedin.com/in/rauchg",
    twitter: "https://twitter.com/rauchg",
    status: "contacted",
    created_at: "2026-06-12T12:00:00Z",
    tag_ids: ["t2", "t7"],
  },
  {
    id: "p3",
    company_id: "c3",
    name: "Ivan Zhao",
    role: "Co-founder",
    email: "ivan@notion.so",
    linkedin: "https://linkedin.com/in/ivanhzhao",
    twitter: null,
    status: "meeting",
    created_at: "2026-06-20T12:00:00Z",
    tag_ids: ["t1", "t4"],
  },
  {
    id: "p4",
    company_id: "c4",
    name: "Thomas Paul Mann",
    role: "Co-founder",
    email: "thomas@raycast.com",
    linkedin: "https://linkedin.com/in/thomaspaulmann",
    twitter: "https://twitter.com/thomaspaulmann",
    status: "new",
    created_at: "2026-07-02T12:00:00Z",
    tag_ids: ["t2"],
  },
  {
    id: "p5",
    company_id: "c2",
    name: "Lee Robinson",
    role: "VP of Product",
    email: "lee@vercel.com",
    linkedin: "https://linkedin.com/in/leeerob",
    twitter: "https://twitter.com/leeerob",
    status: "contacted",
    created_at: "2026-07-05T12:00:00Z",
    tag_ids: ["t3", "t7"],
  },
  {
    id: "p6",
    company_id: "c5",
    name: "Josh Miller",
    role: "CEO",
    email: null,
    linkedin: "https://linkedin.com/in/joshm",
    twitter: "https://twitter.com/joshm",
    status: "closed",
    created_at: "2026-07-10T12:00:00Z",
    tag_ids: ["t5"],
  },
  {
    id: "p7",
    company_id: null,
    name: "Sarah Chen",
    role: "Independent Investor",
    email: "sarah@example.com",
    linkedin: "https://linkedin.com/in/sarahchen",
    twitter: null,
    status: "not_interested",
    created_at: "2026-07-15T12:00:00Z",
    tag_ids: ["t5"],
  },
];
