/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as FollowUpsRouteImport } from './routes/follow-ups'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as CompaniesIdRouteImport } from './routes/companies.$id'
import { Route as ContactsIndexRouteImport } from './routes/contacts.index'
import { Route as ContactsIdRouteImport } from './routes/contacts.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsRoute = FollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompaniesRoute,
} as any)
const CompaniesIdRoute = CompaniesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CompaniesRoute,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContactsRoute,
} as any)
const ContactsIdRoute = ContactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContactsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/contacts': typeof ContactsRouteWithChildren
  '/follow-ups': typeof FollowUpsRoute
  '/outreach': typeof OutreachRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/contacts/': typeof ContactsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/follow-ups': typeof FollowUpsRoute
  '/outreach': typeof OutreachRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/companies': typeof CompaniesIndexRoute
  '/contacts': typeof ContactsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/contacts': typeof ContactsRouteWithChildren
  '/follow-ups': typeof FollowUpsRoute
  '/outreach': typeof OutreachRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/contacts/': typeof ContactsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies'
    | '/contacts'
    | '/follow-ups'
    | '/outreach'
    | '/companies/$id'
    | '/contacts/$id'
    | '/companies/'
    | '/contacts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/follow-ups'
    | '/outreach'
    | '/companies/$id'
    | '/contacts/$id'
    | '/companies'
    | '/contacts'
  id:
    | '__root__'
    | '/'
    | '/companies'
    | '/contacts'
    | '/follow-ups'
    | '/outreach'
    | '/companies/$id'
    | '/contacts/$id'
    | '/companies/'
    | '/contacts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
  ContactsRoute: typeof ContactsRouteWithChildren
  FollowUpsRoute: typeof FollowUpsRoute
  OutreachRoute: typeof OutreachRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups': {
      id: '/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof FollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/companies/$id': {
      id: '/companies/$id'
      path: '/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof CompaniesIdRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof ContactsRoute
    }
    '/contacts/$id': {
      id: '/contacts/$id'
      path: '/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof ContactsIdRouteImport
      parentRoute: typeof ContactsRoute
    }
  }
}

interface CompaniesRouteChildren {
  CompaniesIdRoute: typeof CompaniesIdRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesIdRoute: CompaniesIdRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

interface ContactsRouteChildren {
  ContactsIdRoute: typeof ContactsIdRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
}

const ContactsRouteChildren: ContactsRouteChildren = {
  ContactsIdRoute: ContactsIdRoute,
  ContactsIndexRoute: ContactsIndexRoute,
}

const ContactsRouteWithChildren = ContactsRoute._addFileChildren(
  ContactsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
  ContactsRoute: ContactsRouteWithChildren,
  FollowUpsRoute: FollowUpsRoute,
  OutreachRoute: OutreachRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
